**Task:**
**EDA_OUTLIERS**

You are given height_weight.csv file which contains heights and weights of 1000 people. Dataset is taken from here, https://www.kaggle.com/mustafaali96/weight-height

You need to do this,

(1) Load this csv in pandas dataframe and first plot histograms for height and weight parameters

(2) Using IQR detect weight outliers and print them

(3) Using IQR, detect height outliers and print them

(4) replace the outliers with mean and median and print the dataset

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [1]:
from google.colab import files
uploaded=files.upload()

Saving weight-height.csv to weight-height.csv

In [5]:
import pandas as pd
df=pd.read_csv("weight-height.csv")
df

      Gender     Height      Weight
0       Male  73.847017  241.893563
1       Male  68.781904  162.310473
2       Male  74.110105  212.740856
3       Male  71.730978  220.042470
4       Male  69.881796  206.349801
...      ...        ...         ...
9995  Female  66.172652  136.777454
9996  Female  67.067155  170.867906
9997  Female  63.867992  128.475319
9998  Female  69.034243  163.852461
9999  Female  61.944246  113.649103

[10000 rows x 3 columns]

In [6]:
df.describe()

             Height        Weight
count  10000.000000  10000.000000
mean      66.367560    161.440357
std        3.847528     32.108439
min       54.263133     64.700127
25%       63.505620    135.818051
50%       66.318070    161.212928
75%       69.174262    187.169525
max       78.998742    269.989699

In [8]:
#Detect outliers(height) using IQR
Q1=df.Height.quantile(0.25)
Q3=df.Height.quantile(0.75)
Q1,Q3

(np.float64(63.505620481218955), np.float64(69.1742617268347))

In [9]:
#finding IQR
IQR=Q3-Q1
IQR

np.float64(5.668641245615746)

In [10]:
#finding lower,upper limits
lower_limit = Q1 - 1.5*IQR
upper_limit = Q3 + 1.5*IQR
lower_limit, upper_limit

(np.float64(55.00265861279534), np.float64(77.67722359525831))

In [11]:
#Here are the outliers

df[(df.Height<lower_limit)|(df.Height>upper_limit)]

      Gender     Height      Weight
994     Male  78.095867  255.690835
1317    Male  78.462053  227.342565
2014    Male  78.998742  269.989699
3285    Male  78.528210  253.889004
3757    Male  78.621374  245.733783
6624  Female  54.616858   71.393749
7294  Female  54.873728   78.606670
9285  Female  54.263133   64.700127

In [12]:
# replacing outliers with mean
mean_h = df['Height'].mean()
df['Height'] = df['Height'].apply(
    lambda x: mean_h if x <lower_limit or x > upper_limit else x
)

      Gender     Height      Weight
0       Male  73.847017  241.893563
1       Male  68.781904  162.310473
2       Male  74.110105  212.740856
3       Male  71.730978  220.042470
4       Male  69.881796  206.349801
...      ...        ...         ...
9995  Female  66.172652  136.777454
9996  Female  67.067155  170.867906
9997  Female  63.867992  128.475319
9998  Female  69.034243  163.852461
9999  Female  61.944246  113.649103

[10000 rows x 3 columns]

In [14]:
#Detect outliers(height) using IQR
Q1=df.Weight.quantile(0.25)
Q3=df.Weight.quantile(0.75)
Q1,Q3

(np.float64(135.8180513055015), np.float64(187.16952486868348))

In [15]:
#finding IQR
IQR=Q3-Q1
IQR

np.float64(51.35147356318197)

In [16]:
#finding lower,upper limits
lower_limit = Q1 - 1.5*IQR
upper_limit = Q3 + 1.5*IQR
lower_limit, upper_limit

(np.float64(58.79084096072856), np.float64(264.19673521345646))

In [17]:
#Here are the outliers

df[(df.Weight<lower_limit)|(df.Weight>upper_limit)]

     Gender    Height      Weight
2014   Male  66.36756  269.989699

In [20]:
# replacing outliers with mean
mean_h = df['Weight'].mean()
df['Weight'] = df['Weight'].apply(
    lambda x: mean_h if x <lower_limit or x > upper_limit else x
)

In [21]:
print(df)

      Gender     Height      Weight
0       Male  73.847017  241.893563
1       Male  68.781904  162.310473
2       Male  74.110105  212.740856
3       Male  71.730978  220.042470
4       Male  69.881796  206.349801
...      ...        ...         ...
9995  Female  66.172652  136.777454
9996  Female  67.067155  170.867906
9997  Female  63.867992  128.475319
9998  Female  69.034243  163.852461
9999  Female  61.944246  113.649103

[10000 rows x 3 columns]